#!/usr/bin/env bash
#MISE depends=["build", "build-usage"]

set -eu

hk usage > hk.usage.kdl
rm -rf docs/cli && mkdir -p docs/cli
target/usage-cli/bin/usage g markdown -mf hk.usage.kdl --out-dir docs/cli --url-prefix /cli
target/usage-cli/bin/usage g json -f hk.usage.kdl > docs/cli/commands.json
python3 scripts/enrich-cli-docs.py
prettier --write docs/cli
git add hk.usage.kdl docs
