self-hosted-runner:
  labels:
    - jdx-perf-v1
    - bamboo-perf
    - namespace-profile-endev-linux-amd64
    - namespace-profile-endev-linux-amd64;overrides.cache-tag=cache
    - namespace-profile-endev-linux-arm64;overrides.cache-tag=cache
    - namespace-profile-endev-macos-arm64
    - namespace-profile-endev-macos-arm64;overrides.cache-tag=cache
