use crate::Result;
use crate::cli::Cli;

/// Generates a usage spec for the CLI
///
/// https://usage.jdx.dev
#[derive(Debug, usage_rs::Args)]
#[usage(effect = "read")]
pub struct Usage;

impl Usage {
    pub async fn run(&self) -> Result<()> {
        let spec = Cli::to_kdl();
        // 4.0 added flag-level `effect=`; older `usage` CLIs reject the spec with
        // "unsupported cmd prop effect".
        let usage =
            format!("// @generated by usage-derive metadata\nmin_usage_version \"4.0\"\n{spec}\n")
                + include_str!("../hk-extras.usage.kdl");
        println!("{}", usage.trim());
        Ok(())
    }
}
