#!/usr/bin/env bash
#MISE depends=["build", "test:bats:setup"]
#MISE env = { "HK_LIBGIT2" = "0" }
#USAGE arg "<test>..." default="test"

set -eu

exec "$(dirname "$0")/../../../scripts/run-bats" with-git "$@"
