#!/usr/bin/env bash
#MISE sources=["Cargo.lock"]
#MISE outputs=["target/usage-cli/bin/usage"]

set -eu

cargo install --locked \
  --git https://github.com/jdx/usage \
  --rev 6566acfbb1809a9c545420e18f28d233b1c56676 \
  --root target/usage-cli \
  usage-cli
