#!/usr/bin/env bash
#MISE sources=["Cargo.lock"]
#MISE outputs=["target/usage-cli/bin/usage"]

set -eu

cargo install --locked \
  --git https://github.com/jdx/usage \
  --rev 597f58718a42a9a6e81675af47cc0d50d0273a4a \
  --root target/usage-cli \
  usage-cli
