name: ci-windows

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_EXPERIMENTAL: true
  MISE_DISABLE_TOOLS: hadolint,swiftlint,bun

jobs:
  windows-test:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      
      - name: Install tools with mise
        shell: pwsh
        run: |
          # Install required tools via mise
          mise install
          mise list
      
      - name: Build
        run: mise run build
      
      - name: Run Rust unit tests
        run: mise run test:cargo
      
      - name: Run Windows Pester tests
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck
          Import-Module Pester
          Invoke-Pester -Path "test\windows\hk.Tests.ps1" -Output Detailed
      
      - name: Test hk init
        shell: pwsh
        run: |
          mkdir test-repo
          cd test-repo
          git init
          git config user.email "test@example.com"
          git config user.name "Test User"
          mise x -- hk init
          if (!(Test-Path "hk.pkl")) {
            Write-Error "hk.pkl was not created"
            exit 1
          }
      
      - name: Test hk install/uninstall
        shell: pwsh
        run: |
          cd test-repo
          mise x -- hk install
          if (!(Test-Path ".git\hooks\pre-commit")) {
            Write-Error "pre-commit hook was not created"
            exit 1
          }
          mise x -- hk uninstall
          if (Test-Path ".git\hooks\pre-commit") {
            Write-Error "pre-commit hook was not removed"
            exit 1
          }
      
      - name: Test hk check with PowerShell
        shell: pwsh
        run: |
          mkdir test-ps
          cd test-ps
          git init
          git config user.email "test@example.com"
          git config user.name "Test User"
          
          @'
          amends "package://github.com/jdx/hk/releases/download/v1.2.0/hk@1.2.0#/Config.pkl"
          hooks {
              ["check"] {
                  steps {
                      ["test-ps"] {
                          check = "Write-Host 'PowerShell test passed'"
                          shell = "powershell.exe -NoProfile -Command"
                      }
                  }
              }
          }
          '@ | Out-File -FilePath hk.pkl -Encoding UTF8
          
          $output = mise x -- hk check 2>&1
          if ($LASTEXITCODE -ne 0) {
            Write-Error "hk check failed"
            Write-Host $output
            exit 1
          }
      
      - name: Test hk check with cmd
        shell: cmd
        run: |
          mkdir test-cmd
          cd test-cmd
          git init
          git config user.email "test@example.com"
          git config user.name "Test User"
          
          (
          echo amends "package://github.com/jdx/hk/releases/download/v1.2.0/hk@1.2.0#/Config.pkl"
          echo hooks {
          echo     ["check"] {
          echo         steps {
          echo             ["test-cmd"] {
          echo                 check = "echo CMD test passed"
          echo                 shell = "cmd.exe /C"
          echo             }
          echo         }
          echo     }
          echo }
          ) > hk.pkl
          
          mise x -- hk check
          if %ERRORLEVEL% neq 0 (
            echo hk check failed
            exit /b 1
          )

  windows-build-artifacts:
    runs-on: windows-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/')
    env:
      MISE_EXPERIMENTAL: true
      MISE_DISABLE_TOOLS: hadolint,swiftlint,bun
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      
      - name: Build release binary
        run: mise run build
      
      - name: Package Windows binary
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}"
          mkdir "hk-$version-windows-x64"
          Copy-Item "target\release\hk.exe" "hk-$version-windows-x64\"
          Copy-Item "README.md" "hk-$version-windows-x64\"
          Copy-Item "LICENSE" "hk-$version-windows-x64\"
          Compress-Archive -Path "hk-$version-windows-x64" -DestinationPath "hk-$version-windows-x64.zip"
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: hk-windows-x64
          path: hk-*.zip