name: release-plz

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - release-plz

concurrency:
  group: release-plz

env:
  DRY_RUN: 0

jobs:
  release-plz:
    if: github.repository == 'jdx/hk'
    runs-on: namespace-profile-endev-linux-amd64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.HK_GH_TOKEN }}
      - uses: namespacelabs/nscloud-cache-action@15799a6b54e5765f85b2aac25b3f0df43ed571c0 # v1
        with:
          cache: rust
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          cache_key_prefix: mise-v1-${{ runner.environment }}
          experimental: true
      - run: mise trust --all
      - run: mise run release-plz
        env:
          GITHUB_TOKEN: ${{ secrets.HK_GH_TOKEN }}
